version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-api:prod
    command: gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
      - .env.prod.db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge 